# Generated by Django 4.1.5 on 2023-03-01 12:13

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, upload_to='profle picture')),
                ('about', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('level', models.CharField(choices=[('fresher', 'fresher'), ('intermediate', 'intermediate'), ('professional', 'professional')], default='fresher', max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('year_of_experience', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.companydepartment')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerSkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField(blank=True)),
                ('skill_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.skill')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_url', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, upload_to='', verbose_name='/company_logo')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=50)),
                ('college_name', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_graduated', models.BooleanField(blank=True, default=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='resume')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('is_decline', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=True)),
                ('applied_on', models.DateField(auto_now_add=True, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.company')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile')),
            ],
        ),
    ]
