# Generated by Django 4.1.5 on 2023-03-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('employer_id', models.CharField(blank=True, default=1, max_length=50, null=True, unique=True)),
                ('company_logo', models.ImageField(blank=True, upload_to='media/<django.db.models.fields.CharField>/logo')),
                ('started_date', models.DateField(auto_now_add=True, null=True)),
                ('about', models.TextField(blank=True, max_length=3000)),
                ('founder', models.CharField(blank=True, max_length=200)),
                ('ceo_name', models.CharField(blank=True, max_length=200)),
                ('head_office_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('internship', 'Internship'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='fresher', max_length=200)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=20, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('part-time', 'Part Time'), ('full-time', 'Full Time'), ('intern', 'Intern')], default='full-time', max_length=200)),
                ('full_description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('vacancy', models.PositiveIntegerField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('reports', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postable_job_count', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_active_job', models.BooleanField(default=True)),
                ('activation_date', models.DateField(auto_now_add=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistedCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Shortlised', 'Shortlised'), ('Tech-Interview', 'Tech-Interview'), ('HR-Round', 'HR-Round')], default='Shortlised', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Trial', max_length=200)),
                ('duration', models.IntegerField(choices=[(0, '15 days'), (30, 'One Month'), (90, 'Three Month'), (180, 'Six Month')], default=15)),
                ('price', models.CharField(default=0.0, max_length=200)),
                ('job_count', models.PositiveBigIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.usermembership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.company')),
            ],
        ),
    ]
