# Generated by Django 4.1.5 on 2023-01-30 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('employer_id', models.CharField(blank=True, default=1, max_length=50, null=True, unique=True)),
                ('company_logo', models.ImageField(blank=True, upload_to='media/<django.db.models.fields.CharField>/logo')),
                ('started_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('about', models.TextField(blank=True, max_length=3000)),
                ('founder', models.CharField(blank=True, max_length=200)),
                ('ceo_name', models.CharField(blank=True, max_length=200)),
                ('head_office_location', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superuser.companycategory')),
                ('recruiter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='fresher', max_length=200)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('min_salary', models.IntegerField(blank=True)),
                ('max_salary', models.IntegerField(blank=True)),
                ('job_type', models.CharField(blank=True, choices=[('part-time', 'Part Time'), ('full-time', 'Full Time'), ('intern', 'Intern'), ('work-from-home', 'Work From Home')], default='full-time', max_length=200)),
                ('full_description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.companydepartment')),
                ('qualification', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.qualification')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
