# Generated by Django 4.1.5 on 2023-03-01 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0001_initial'),
        ('seeker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedcandidates',
            name='applied_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.appliedjobs'),
        ),
        migrations.AddField(
            model_name='shortlistedcandidates',
            name='recruiter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.company'),
        ),
        migrations.AddField(
            model_name='membershippurchase',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.usermembership'),
        ),
        migrations.AddField(
            model_name='membershippurchase',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruiter.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.companydepartment'),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.qualification'),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superuser.companycategory'),
        ),
        migrations.AddField(
            model_name='company',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
