# Generated by Django 4.1.5 on 2023-03-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postable_job_count', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_active_job', models.BooleanField(default=True)),
                ('activation_date', models.DateField(auto_now_add=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistedCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Shortlised', 'Shortlised'), ('Tech-Interview', 'Tech-Interview'), ('HR-Round', 'HR-Round')], default='Shortlised', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Trial', max_length=200)),
                ('duration', models.IntegerField(choices=[(0, '15 days'), (30, 'One Month'), (90, 'Three Month'), (180, 'Six Month')], default=15)),
                ('price', models.CharField(default=0.0, max_length=200)),
                ('job_count', models.PositiveBigIntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='min_salary',
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reports',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='started_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('part-time', 'Part Time'), ('full-time', 'Full Time'), ('intern', 'Intern')], default='full-time', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('internship', 'Internship'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='fresher', max_length=200),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.usermembership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.company')),
            ],
        ),
    ]
