# Generated by Django 4.1.5 on 2023-03-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_membershippurchase_shortlistedcandidates_and_more'),
        ('seeker', '0002_rename_country_seekerprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedcandidates',
            name='applied_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.appliedjobs'),
        ),
        migrations.AddField(
            model_name='shortlistedcandidates',
            name='recruiter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.company'),
        ),
        migrations.AddField(
            model_name='membershippurchase',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.usermembership'),
        ),
        migrations.AddField(
            model_name='membershippurchase',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruiter.company'),
        ),
    ]
